FROM node:18-alpine

WORKDIR /app

# Копирование файлов зависимостей
COPY package*.json ./

# Установка зависимостей
RUN npm ci

# Копирование исходного кода
COPY . .

EXPOSE 3000

# Запуск dev сервера Vite
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
